# Generated by Django 4.2.4 on 2023-08-19 13:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutS1', models.TextField(blank=True, default='Section_1', max_length=1000, null=True)),
                ('aboutS2', models.TextField(blank=True, default='Section_2', max_length=1000, null=True)),
                ('aboutS3', models.TextField(blank=True, default='Section_3', max_length=1000, null=True)),
                ('aboutS4', models.TextField(blank=True, default='Section_4', max_length=1000, null=True)),
                ('aboutSkills', models.TextField(blank=True, default='Skills', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, default='Logo', max_length=100, null=True)),
                ('plogName', models.CharField(blank=True, default='Plog_Name', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=200, null=True)),
                ('name_l', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(blank=True, default='default/user3.png', null=True, upload_to='images/%y/%m/%d')),
                ('assistant', models.BooleanField(blank=True, default=False, null=True)),
                ('admin', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Project-Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Project-Description', max_length=400, null=True)),
                ('img', models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d')),
                ('link', models.CharField(blank=True, default='none', max_length=300, null=True)),
                ('html', models.BooleanField(blank=True, default=False, null=True)),
                ('js', models.BooleanField(blank=True, default=False, null=True)),
                ('dj', models.BooleanField(blank=True, default=False, null=True)),
                ('css', models.BooleanField(blank=True, default=False, null=True)),
                ('py', models.BooleanField(blank=True, default=False, null=True)),
                ('bootS', models.BooleanField(blank=True, default=False, null=True)),
                ('bostG', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('github', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=1000, null=True)),
                ('watsapp', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=200, null=True)),
                ('name_l', models.CharField(max_length=200, null=True)),
                ('name_for_nonUser', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('msg', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 8, 19, 16, 12, 8, 837407))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserMsg', to='data.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d')),
                ('img2', models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d')),
                ('img3', models.ImageField(blank=True, default='default/project.png', null=True, upload_to='projects/%d')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='data.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 8, 19, 16, 12, 8, 837407))),
                ('best', models.BooleanField(blank=True, default=False, null=True)),
                ('favourite', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='data.profile')),
            ],
        ),
    ]
